"""Framework-independent business contracts for ZS32 inspection."""

from .contracts import (
    AnomalyBinding,
    AnomalyFamily,
    ArtifactRef,
    DeploymentContract,
    InspectionRecipe,
    ReleaseManifest,
    RequiredEvidenceGroup,
    RoiBox,
    RoiConfig,
    RoiHandConfig,
    RoiReadiness,
    TemplateBinding,
    TemplateThresholdRecord,
    ThresholdRecord,
    canonical_sha256,
)
from .decisions import InspectionDecision, InspectionStatus
from .errors import (
    ConfigLoadError,
    DecisionValidationError,
    DeploymentContractError,
    EvidenceValidationError,
    IdentityValidationError,
    RecipeValidationError,
    RoiValidationError,
    SchemaValidationError,
    TopologyValidationError,
    ZS32ContractError,
)
from .evidence import EvidenceBranch, EvidenceLevel, ModelEvidence, TemplateEvidence, TemplateOutcome
from .identity import CaptureSet, Hand, PartIdentity, RoiSample, ViewImage
from .topology import CameraSlot, CaptureRound, CaptureTopology

__all__ = [
    "AnomalyBinding",
    "AnomalyFamily",
    "ArtifactRef",
    "CameraSlot",
    "CaptureRound",
    "CaptureSet",
    "CaptureTopology",
    "ConfigLoadError",
    "DecisionValidationError",
    "DeploymentContract",
    "DeploymentContractError",
    "EvidenceBranch",
    "EvidenceLevel",
    "EvidenceValidationError",
    "Hand",
    "IdentityValidationError",
    "InspectionDecision",
    "InspectionRecipe",
    "InspectionStatus",
    "ModelEvidence",
    "PartIdentity",
    "RecipeValidationError",
    "ReleaseManifest",
    "RequiredEvidenceGroup",
    "RoiBox",
    "RoiConfig",
    "RoiHandConfig",
    "RoiReadiness",
    "RoiSample",
    "RoiValidationError",
    "SchemaValidationError",
    "TemplateBinding",
    "TemplateEvidence",
    "TemplateOutcome",
    "TemplateThresholdRecord",
    "ThresholdRecord",
    "TopologyValidationError",
    "ViewImage",
    "ZS32ContractError",
    "canonical_sha256",
]
